# Notes TUI Configuration
# This file contains all configuration for the TUI application

# Path to your main notes directory (where your markdown files live)
notes_directory: "/home/brassy/Docker/notes"

# Path to templates directory (shared with main notes project)
templates_directory: "/home/brassy/Docker/notes/.templates"

# Editor settings
editor:
  # Default editor to use (nano, vim, nvim, etc.)
  default: "nano"
  # Alternative editors in order of preference if default is not available
  alternatives:
    - "vim"
    - "vi"
  # Additional arguments to pass to the editor
  args: []

# UI layout settings
ui:
  # Show tree view on startup
  show_tree: true
  # Show preview pane by default
  show_preview: true
  # Tree view width (percentage of screen)
  tree_width: 30
  # Preview pane width (percentage of remaining space)
  preview_width: 50
  # Theme (dark, light, or custom)
  theme: "dark"

# Keybindings
keybindings:
  # Quick capture - create new note
  new_note: "n"
  # Edit selected note
  edit_note: "e"
  # Delete selected note
  delete_note: "d"
  # Search notes
  search: "/"
  # Toggle preview pane
  toggle_preview: "p"
  # Refresh tree view
  refresh: "r"
  # Quit application
  quit: "q"
  # Help screen
  help: "?"

# Quick capture settings
quick_capture:
  # Open editor immediately after entering note name
  instant_edit: true
  # Default category for quick notes
  default_category: "personal"
  # Default template for quick notes
  default_template: "general_note.md"
  # Automatically add timestamp to note name
  auto_timestamp: false

# File watching (for auto-refresh)
watch:
  enabled: true
  # Debounce time in seconds
  debounce: 1.0
